import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parse, stringify } from "yaml";

export type DocumentType = "docx" | "xlsx" | "pptx";

export interface Author {
  name: string;
  email?: string;
}

export interface DocuGitConfig {
  version: number;
  document: {
    type: DocumentType;
    originalName: string;
    createdAt: string;
  };
  authors: Author[];
  stats: {
    lastModifiedBy?: string;
    totalCommits: number;
  };
}

import { DOCUGIT_VERSION } from "../version.ts";

export const DOCUGIT_CONFIG_FILE = ".docugit.yml";

export { DOCUGIT_VERSION };

export function detectDocumentType(filename: string): DocumentType | null {
  const ext = filename.toLowerCase().split(".").pop();
  if (ext === "docx") return "docx";
  if (ext === "xlsx") return "xlsx";
  if (ext === "pptx") return "pptx";
  return null;
}

export function getExtension(type: DocumentType): string {
  return type;
}

export function formatDocumentFilename(originalName: string, type: DocumentType): string {
  return originalName.endsWith(`.${type}`) ? originalName : `${originalName}.${type}`;
}

export function normalizeDocumentName(name: string, type: DocumentType): string {
  const trimmed = name.trim();
  if (!trimmed) {
    throw new Error("fatal: document name must not be empty");
  }
  if (/[/\\]/.test(trimmed)) {
    throw new Error("fatal: document name must not contain path separators");
  }

  const detected = detectDocumentType(trimmed);
  if (detected) {
    if (detected !== type) {
      throw new Error(`fatal: document name extension must be .${type}`);
    }
    return trimmed;
  }

  return `${trimmed}.${type}`;
}

export async function readConfig(repoRoot: string): Promise<DocuGitConfig> {
  const content = await readFile(join(repoRoot, DOCUGIT_CONFIG_FILE), "utf-8");
  return parse(content) as DocuGitConfig;
}

export async function writeConfig(repoRoot: string, config: DocuGitConfig): Promise<void> {
  await writeFile(join(repoRoot, DOCUGIT_CONFIG_FILE), stringify(config), "utf-8");
}

export function createDefaultConfig(
  type: DocumentType,
  originalName: string,
  authors: Author[] = [],
): DocuGitConfig {
  return {
    version: 1,
    document: {
      type,
      originalName,
      createdAt: new Date().toISOString(),
    },
    authors,
    stats: {
      totalCommits: 0,
    },
  };
}

export async function generateReadme(repoRoot: string, config: DocuGitConfig): Promise<void> {
  const authors =
    config.authors.length > 0
      ? config.authors.map((a) => (a.email ? `${a.name} <${a.email}>` : a.name)).join(", ")
      : "not set";

  const content = `# ${config.document.originalName}

This repository was auto-generated by [DocuGit](https://github.com/xiaoheiCat/docugit). Open it with DocuGit.

## Metadata

| Field | Value |
|-------|-------|
| Document type | ${config.document.type} |
| Original filename | ${config.document.originalName} |
| Created at | ${config.document.createdAt} |
| DocuGit version | ${DOCUGIT_VERSION} |
| Authors | ${authors} |
| Last modified by | ${config.stats.lastModifiedBy ?? "unknown"} |
| Total commits | ${config.stats.totalCommits} |

## Quick start

\`\`\`bash
docugit open      # Open and edit in Office
docugit diff      # View semantic changes
docugit export    # Export as an Office file
\`\`\`
`;
  await writeFile(join(repoRoot, "README.md"), content, "utf-8");
}

export async function isDocuGitRepo(repoRoot: string): Promise<boolean> {
  try {
    await readConfig(repoRoot);
    return true;
  } catch {
    return false;
  }
}
