import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import JSZip from "jszip";
import type { DocumentType } from "../src/config/docugit-yml.ts";

const ROOT = join(import.meta.dir, "..");
const TEMPLATES_DIR = join(ROOT, "templates");
const OUT_DIR = join(ROOT, "src/generated");
const OUT_FILE = join(OUT_DIR, "embedded-templates.ts");

const TEMPLATE_TYPES: DocumentType[] = ["docx", "xlsx", "pptx"];

async function zipTemplateDir(type: DocumentType): Promise<string> {
  const zip = new JSZip();

  async function walk(dir: string, prefix: string): Promise<void> {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const fullPath = join(dir, entry.name);
      const zipPath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        await walk(fullPath, zipPath);
      } else {
        zip.file(zipPath, await readFile(fullPath));
      }
    }
  }

  await walk(join(TEMPLATES_DIR, type), "");
  return (await zip.generateAsync({ type: "base64", compression: "DEFLATE" })) as string;
}

const bundles: Record<DocumentType, string> = {
  docx: await zipTemplateDir("docx"),
  xlsx: await zipTemplateDir("xlsx"),
  pptx: await zipTemplateDir("pptx"),
};

const content = `// Generated by scripts/embed-templates.ts — do not edit.
import type { DocumentType } from "../config/docugit-yml.ts";

export const EMBEDDED_TEMPLATE_ZIPS: Record<DocumentType, Uint8Array> = {
  docx: Uint8Array.from(atob(${JSON.stringify(bundles.docx)}), (c) => c.charCodeAt(0)),
  xlsx: Uint8Array.from(atob(${JSON.stringify(bundles.xlsx)}), (c) => c.charCodeAt(0)),
  pptx: Uint8Array.from(atob(${JSON.stringify(bundles.pptx)}), (c) => c.charCodeAt(0)),
};
`;

await mkdir(OUT_DIR, { recursive: true });
await writeFile(OUT_FILE, content);
console.log(`Wrote ${OUT_FILE}`);
